server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.174.131
aliyun:
  sms:
    accessKeyId: 不告诉你
    accessKeySecret: 不告诉你
    template_code: SMS_85735065
    sign_name: 黑马
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka

# 日志
logging:
  config: classpath:log.xml