spring:
  profiles:
    active: '@spring.active@'

application:
  version: @project.version@

# 服务端口号
server:
  port: 9004
  application:
    name: tensquare-friend

mybatis-plus:
  mapper-locations: classpath:mapper/*/**.xml
