server:
  port: 9003
application:
  version: @project.version@
spring:
  application:
    name: tensquare-qa
  profiles:
    active: '@spring.active@'

mybatis-plus:
  mapper-locations: classpath:mapper/qa/*.xml

jwt:
  config:
    key: emuel
    ttl: 60000