#
spring:
  application:
    name: tensquare-article
  profiles:
    active: dev
#   active: prod

# 服务端口号
server:
  port: 9004


# 日志
logging:
  config: classpath:log.xml


mybatis-plus:
  mapper-locations: classpath:mapper/article/*.xml


