server:
  port: 9001
spring:
  application:
    name: tensquare-base
  profiles:
    active: dev

# 日志
logging:
  config: classpath:log.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*/**Mapper.xml