spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://192.168.20.129:3306/tensquare_base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123@eCloud
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service‐url:
      defaultZone: http://192.168.20.129:6868/eureka
  instance:
    prefer‐ip‐address: true