server:
  port: 9001
spring:
  application:
    name: tensquareBase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: demo
    password: root123@eCloud
  jpa:
    database: mysql
    show-sql: true
# 日志
logging:
  config: classpath:log.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml