server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/emmanuelHan/tenSquare.git
  rabbitmq:
    host: 192.168.20.129
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh