server:
  port: 9009
spring:
  application:
    name: tensquareSms
  rabbitmq:
    host: 192.168.174.131
aliyun:
  sms:
    accessKeyId: 不告诉你
    accessKeySecret: 不告诉你
    template_code: SMS_85735065
    sign_name: 黑马
