server:
  port: 9108
spring:
  rabbitmq:
    host: 192.168.174.131
# 日志
logging:
  config: classpath:log.xml
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true