application:
  version: @project.version@
server:
  port: 9108
spring:
  application:
    name: tensquare-rabbitmq
  rabbitmq:
    username: root
    password: root123@eCloud
    host: 10.0.31.100
    port: 5671
    cache:
      channel:
        size: 50 # 缓存的Channel数量
    virtual-host: /
    publisher-confirms: true
    ssl:
      enabled: true
      key-store: classpath:client_localhost_key.p12
      key-store-password:
      trust-store: classpath:server.keystore
      trust-store-password: root123@eCloud
      algorithm: TLSv1.2
      trust-store-type: JKS
      key-store-type: PKCS12
      validate-server-certificate: true
      verify-hostname: false
    listener:
      feedback:
        exchange:
          durable: true
          ignoreDeclarationExceptions: true
          key: Queue1
          name: TEST
          type: direct
        queue:
          durable: true
          name: Queue1



eureka:
  client:
    service‐url:
      defaultZone: http://192.168.20.129:6868/eureka
  instance:
    prefer‐ip‐address: true