#
spring:
  profiles:
#    active: laptop
    active: dev
#   active: prod

# 服务端口号
server:
  port: 9004
  application:
    name: tensquare-friend

# 日志
logging:
  config: classpath:log.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*/**.xml
