server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.174.131
      database: spitDb
  redis:
    host: 192.168.174.131
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true

# 日志
logging:
  config: classpath:log.xml