# 数据源
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://@service.ip@:3306/tensquare_article?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接数，最小，最大连接数
      initial-size: 5
      min-idle: 5
      max-active: 20
      #获取连接超时时间
      max-wait: 60000
      #监控后台账号
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: ${ip}
    username: admin
    password: admin
  data:
    mongodb:
      database: commentDb
      host: @service.ip@
  redis:
    host: @service.ip@
#eureka:
#  client:
#    service‐url:
#      defaultZone: http://127.0.0.1:6868/eureka
#  instance:
#    prefer‐ip‐address: true
jasypt:
  encryptor:
    password: atpingan
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
smalldoc:
#  source-paths: #额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
#    - 'D:\Workspaces\myBeanProject\my-bean\src\main\java'
#    - 'D:\Maven\Repositories\repository\com\aliyun\aliyun-java-sdk-core\3.5.0'
  packages:
#    - quantity.knowledgebase
#    - my.bean
    - com.tensquare.article
  project-name: 我的文档
  enabled: true #默认为true
  url-pattern: /smalldoc/* #默认为/smalldoc/*
