server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/emmanuelHan/tenSquare.git
  rabbitmq:
    host: 10.0.50.55

application:
  version: @project.version@

#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh