# 服务端口号
server:
  port: 9008

# 数据源
spring:
  application:
    name: tensquare-user
  profiles:
#    active: laptop
    active: dev
  main:
    allow-bean-definition-overriding: true

# 日志
logging:
  config: classpath:log.xml