server:
  port: 9002
application:
  version: @project.version@
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.129:3306/tensquare_recruit?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: demo
    password: root123@eCloud
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service‐url:
      defaultZone: http://192.168.20.129:6868/eureka
  instance:
    prefer‐ip‐address: true