# 服务端口号
server:
  port: 9008
application:
  version: 1.0.0

# 数据源
spring:
  application:
    name: tensquare-user
  profiles:
    active: '@spring.active@'
  main:
    allow-bean-definition-overriding: true
jwt:
  config:
    key: emuel
    ttl: 3600000
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: state  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)