ip: 10.0.50.55
# 数据源
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://${ip}:3306/tensquare_user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123@eCloud
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
#  redis:
#    host: ${ip}
#  rabbitmq:
#    host: ${ip}
eureka:
  client:
    service‐url:
      defaultZone: http://${ip}:6868/eureka
  instance:
    prefer‐ip‐address: true